// Dosya uzantısından dil tespiti
export function getLanguageFromPath(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    ts: "typescript",
    tsx: "typescript",
    js: "javascript",
    jsx: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    py: "python",
    rb: "ruby",
    go: "go",
    rs: "rust",
    java: "java",
    kt: "kotlin",
    swift: "swift",
    c: "c",
    cpp: "cpp",
    cc: "cpp",
    h: "cpp",
    hpp: "cpp",
    cs: "csharp",
    php: "php",
    html: "html",
    htm: "html",
    css: "css",
    scss: "scss",
    sass: "scss",
    less: "less",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    xml: "xml",
    md: "markdown",
    mdx: "markdown",
    sh: "shell",
    bash: "shell",
    zsh: "shell",
    sql: "sql",
    graphql: "graphql",
    gql: "graphql",
    vue: "html",
    svelte: "html",
    dockerfile: "dockerfile",
    txt: "plaintext",
    env: "ini",
    ini: "ini",
    conf: "ini",
    log: "plaintext",
  };
  return map[ext] ?? "plaintext";
}

export const LANGUAGE_ICONS: Record<string, string> = {
  typescript: "TS",
  javascript: "JS",
  python: "PY",
  go: "GO",
  rust: "RS",
  java: "JVM",
  ruby: "RB",
  php: "PHP",
  html: "<>",
  css: "#",
  json: "{}",
  markdown: "MD",
  shell: "$",
  sql: "DB",
};

export function getLanguageColor(language: string): string {
  const colors: Record<string, string> = {
    typescript: "#3178c6",
    javascript: "#f7df1e",
    python: "#3572A5",
    go: "#00ADD8",
    rust: "#dea584",
    java: "#b07219",
    ruby: "#701516",
    php: "#4F5D95",
    html: "#e34c26",
    css: "#563d7c",
    json: "#292929",
    markdown: "#083fa1",
    shell: "#89e051",
    sql: "#e38c00",
  };
  return colors[language] ?? "#6b7280";
}
