import type { ProviderConfig, ProviderId } from "@/types";

export const PROVIDERS: Record<ProviderId, ProviderConfig> = {
  openai: {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4, GPT-4o, o1, o3 serisi modeller",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    baseUrl: "https://api.openai.com/v1",
    authHeader: "bearer",
    color: "#10a37f",
    icon: "openai",
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        contextWindow: 128000,
        inputCostPer1k: 0.0025,
        outputCostPer1k: 0.01,
        capabilities: ["code", "reasoning", "vision", "long-context"],
        tier: "balanced",
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        contextWindow: 128000,
        inputCostPer1k: 0.00015,
        outputCostPer1k: 0.0006,
        capabilities: ["code", "fast", "vision"],
        tier: "fast",
      },
      {
        id: "o1",
        name: "o1",
        contextWindow: 200000,
        inputCostPer1k: 0.015,
        outputCostPer1k: 0.06,
        capabilities: ["reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        contextWindow: 200000,
        inputCostPer1k: 0.0011,
        outputCostPer1k: 0.0044,
        capabilities: ["reasoning", "code"],
        tier: "balanced",
      },
    ],
  },

  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude 3.5 Sonnet, Opus, Haiku modelleri",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    baseUrl: "https://api.anthropic.com/v1",
    authHeader: "x-api-key",
    apiVersion: "2023-06-01",
    color: "#d97757",
    icon: "anthropic",
    models: [
      {
        id: "claude-3-5-sonnet-20241022",
        name: "Claude 3.5 Sonnet",
        contextWindow: 200000,
        inputCostPer1k: 0.003,
        outputCostPer1k: 0.015,
        capabilities: ["code", "reasoning", "vision", "long-context"],
        tier: "powerful",
      },
      {
        id: "claude-3-5-haiku-20241022",
        name: "Claude 3.5 Haiku",
        contextWindow: 200000,
        inputCostPer1k: 0.0008,
        outputCostPer1k: 0.004,
        capabilities: ["code", "fast", "vision"],
        tier: "fast",
      },
      {
        id: "claude-3-opus-20240229",
        name: "Claude 3 Opus",
        contextWindow: 200000,
        inputCostPer1k: 0.015,
        outputCostPer1k: 0.075,
        capabilities: ["code", "reasoning", "long-context", "creative"],
        tier: "powerful",
      },
    ],
  },

  google: {
    id: "google",
    name: "Google Gemini",
    description: "Gemini 2.5 Pro/Flash, 2.0 Flash, 1.5 - en güncel modeller",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authHeader: "google",
    color: "#4285f4",
    icon: "google",
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        contextWindow: 2000000,
        inputCostPer1k: 0.00125,
        outputCostPer1k: 0.01,
        capabilities: ["code", "reasoning", "vision", "long-context", "creative"],
        tier: "powerful",
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        contextWindow: 1000000,
        inputCostPer1k: 0.00015,
        outputCostPer1k: 0.0006,
        capabilities: ["code", "reasoning", "vision", "long-context", "fast"],
        tier: "balanced",
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash Lite",
        contextWindow: 1000000,
        inputCostPer1k: 0.0000375,
        outputCostPer1k: 0.00015,
        capabilities: ["code", "vision", "fast"],
        tier: "fast",
      },
      {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash",
        contextWindow: 1000000,
        inputCostPer1k: 0.0001,
        outputCostPer1k: 0.0004,
        capabilities: ["code", "vision", "long-context", "fast"],
        tier: "balanced",
      },
      {
        id: "gemini-2.0-flash-thinking-exp",
        name: "Gemini 2.0 Flash Thinking (Exp)",
        contextWindow: 1000000,
        inputCostPer1k: 0.0001,
        outputCostPer1k: 0.0004,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        contextWindow: 2000000,
        inputCostPer1k: 0.00125,
        outputCostPer1k: 0.005,
        capabilities: ["code", "reasoning", "vision", "long-context"],
        tier: "powerful",
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        contextWindow: 1000000,
        inputCostPer1k: 0.000075,
        outputCostPer1k: 0.0003,
        capabilities: ["code", "vision", "long-context", "fast"],
        tier: "fast",
      },
      {
        id: "gemini-1.5-flash-8b",
        name: "Gemini 1.5 Flash 8B",
        contextWindow: 1000000,
        inputCostPer1k: 0.0000375,
        outputCostPer1k: 0.00015,
        capabilities: ["code", "fast"],
        tier: "fast",
      },
      {
        id: "gemini-exp-1206",
        name: "Gemini Exp 1206",
        contextWindow: 2000000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "reasoning", "vision", "long-context"],
        tier: "powerful",
      },
    ],
  },

  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek Coder, V3, R1 modelleri",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    baseUrl: "https://api.deepseek.com/v1",
    authHeader: "bearer",
    color: "#4d6bfe",
    icon: "deepseek",
    models: [
      {
        id: "deepseek-coder",
        name: "DeepSeek Coder",
        contextWindow: 128000,
        inputCostPer1k: 0.00014,
        outputCostPer1k: 0.00028,
        capabilities: ["code", "long-context"],
        tier: "balanced",
      },
      {
        id: "deepseek-chat",
        name: "DeepSeek V3",
        contextWindow: 64000,
        inputCostPer1k: 0.00014,
        outputCostPer1k: 0.00028,
        capabilities: ["code", "reasoning"],
        tier: "balanced",
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek R1",
        contextWindow: 64000,
        inputCostPer1k: 0.00055,
        outputCostPer1k: 0.00219,
        capabilities: ["reasoning", "code"],
        tier: "powerful",
      },
    ],
  },

  xai: {
    id: "xai",
    name: "xAI Grok",
    description: "Grok-2, Grok-3 modelleri",
    apiKeyUrl: "https://x.ai/api",
    baseUrl: "https://api.x.ai/v1",
    authHeader: "bearer",
    color: "#000000",
    icon: "xai",
    models: [
      {
        id: "grok-2-latest",
        name: "Grok-2",
        contextWindow: 131072,
        inputCostPer1k: 0.002,
        outputCostPer1k: 0.01,
        capabilities: ["code", "reasoning", "creative"],
        tier: "balanced",
      },
      {
        id: "grok-3-beta",
        name: "Grok-3",
        contextWindow: 131072,
        inputCostPer1k: 0.003,
        outputCostPer1k: 0.015,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "grok-3-mini",
        name: "Grok-3 Mini",
        contextWindow: 131072,
        inputCostPer1k: 0.0003,
        outputCostPer1k: 0.0005,
        capabilities: ["code", "fast", "reasoning"],
        tier: "fast",
      },
    ],
  },

  ollama: {
    id: "ollama",
    name: "Ollama (Yerel)",
    description: "Llama, Mistral, Qwen - yerel modeller",
    apiKeyUrl: "https://ollama.ai/download",
    baseUrl: "http://localhost:11434",
    authHeader: "none",
    color: "#22b8cf",
    icon: "ollama",
    models: [
      {
        id: "llama3.2",
        name: "Llama 3.2",
        contextWindow: 128000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "reasoning"],
        tier: "balanced",
      },
      {
        id: "qwen2.5-coder",
        name: "Qwen 2.5 Coder",
        contextWindow: 128000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "long-context"],
        tier: "balanced",
      },
      {
        id: "mistral",
        name: "Mistral",
        contextWindow: 32000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "fast"],
        tier: "fast",
      },
    ],
  },

  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    description: "Tüm sağlayıcılara tek API üzerinden erişim",
    apiKeyUrl: "https://openrouter.ai/keys",
    baseUrl: "https://openrouter.ai/api/v1",
    authHeader: "bearer",
    color: "#8b5cf6",
    icon: "openrouter",
    models: [
      {
        id: "anthropic/claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet",
        contextWindow: 200000,
        inputCostPer1k: 0.003,
        outputCostPer1k: 0.015,
        capabilities: ["code", "reasoning", "vision"],
        tier: "powerful",
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        contextWindow: 128000,
        inputCostPer1k: 0.0025,
        outputCostPer1k: 0.01,
        capabilities: ["code", "reasoning", "vision"],
        tier: "balanced",
      },
      {
        id: "google/gemini-2.0-flash-001",
        name: "Gemini 2.0 Flash",
        contextWindow: 1000000,
        inputCostPer1k: 0.0001,
        outputCostPer1k: 0.0004,
        capabilities: ["code", "fast", "vision"],
        tier: "fast",
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1",
        contextWindow: 64000,
        inputCostPer1k: 0.00055,
        outputCostPer1k: 0.00219,
        capabilities: ["reasoning", "code"],
        tier: "powerful",
      },
    ],
  },

  zhipu: {
    id: "zhipu",
    name: "Zhipu (Z.ai)",
    description: "GLM-4, GLM-4V, GLM-4-Plus, GLM-4-Flash - Z.ai modelleri",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    authHeader: "bearer",
    color: "#3b82f6",
    icon: "zhipu",
    models: [
      {
        id: "glm-4-plus",
        name: "GLM-4-Plus",
        contextWindow: 128000,
        inputCostPer1k: 0.0035,
        outputCostPer1k: 0.0035,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "glm-4",
        name: "GLM-4",
        contextWindow: 128000,
        inputCostPer1k: 0.0014,
        outputCostPer1k: 0.0014,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "balanced",
      },
      {
        id: "glm-4v",
        name: "GLM-4V (Vision)",
        contextWindow: 128000,
        inputCostPer1k: 0.0014,
        outputCostPer1k: 0.0014,
        capabilities: ["code", "reasoning", "vision", "long-context"],
        tier: "balanced",
      },
      {
        id: "glm-4-flash",
        name: "GLM-4-Flash",
        contextWindow: 128000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "fast"],
        tier: "fast",
      },
      {
        id: "glm-4-long",
        name: "GLM-4-Long",
        contextWindow: 1000000,
        inputCostPer1k: 0.001,
        outputCostPer1k: 0.001,
        capabilities: ["long-context", "code"],
        tier: "balanced",
      },
      {
        id: "glm-4-flashx",
        name: "GLM-4-FlashX",
        contextWindow: 128000,
        inputCostPer1k: 0,
        outputCostPer1k: 0,
        capabilities: ["code", "fast", "reasoning"],
        tier: "fast",
      },
    ],
  },

  perplexity: {
    id: "perplexity",
    name: "Perplexity",
    description: "Son Llama modelleri + web arama (sonyx.ai)",
    apiKeyUrl: "https://www.perplexity.ai/settings/api",
    baseUrl: "https://api.perplexity.ai",
    authHeader: "bearer",
    color: "#20b8cd",
    icon: "perplexity",
    models: [
      {
        id: "llama-3.1-sonar-large-128k-online",
        name: "Sonar Large Online",
        contextWindow: 127072,
        inputCostPer1k: 0.001,
        outputCostPer1k: 0.001,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "llama-3.1-sonar-small-128k-online",
        name: "Sonar Small Online",
        contextWindow: 127072,
        inputCostPer1k: 0.0002,
        outputCostPer1k: 0.0002,
        capabilities: ["code", "fast", "long-context"],
        tier: "fast",
      },
      {
        id: "llama-3.1-70b-instruct",
        name: "Llama 3.1 70B",
        contextWindow: 127072,
        inputCostPer1k: 0.0007,
        outputCostPer1k: 0.0007,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "balanced",
      },
    ],
  },

  mistral: {
    id: "mistral",
    name: "Mistral",
    description: "Mistral Large, Codestral, Mixtral modelleri",
    apiKeyUrl: "https://console.mistral.ai/api-keys",
    baseUrl: "https://api.mistral.ai/v1",
    authHeader: "bearer",
    color: "#ff7000",
    icon: "mistral",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        contextWindow: 128000,
        inputCostPer1k: 0.002,
        outputCostPer1k: 0.006,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        contextWindow: 32000,
        inputCostPer1k: 0.001,
        outputCostPer1k: 0.003,
        capabilities: ["code", "fast"],
        tier: "balanced",
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        contextWindow: 32000,
        inputCostPer1k: 0.0002,
        outputCostPer1k: 0.0006,
        capabilities: ["code", "fast"],
        tier: "fast",
      },
      {
        id: "open-mixtral-8x7b",
        name: "Mixtral 8x7B",
        contextWindow: 32000,
        inputCostPer1k: 0.0007,
        outputCostPer1k: 0.0007,
        capabilities: ["code", "reasoning"],
        tier: "balanced",
      },
    ],
  },

  cohere: {
    id: "cohere",
    name: "Cohere",
    description: "Command R+, Command R, Aya modelleri",
    apiKeyUrl: "https://dashboard.cohere.com/api-keys",
    baseUrl: "https://api.cohere.com/v2",
    authHeader: "bearer",
    color: "#39594d",
    icon: "cohere",
    models: [
      {
        id: "command-r-plus-08-2024",
        name: "Command R+",
        contextWindow: 128000,
        inputCostPer1k: 0.0025,
        outputCostPer1k: 0.01,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "command-r-08-2024",
        name: "Command R",
        contextWindow: 128000,
        inputCostPer1k: 0.00015,
        outputCostPer1k: 0.0006,
        capabilities: ["code", "long-context"],
        tier: "balanced",
      },
      {
        id: "command-r7b-12-2024",
        name: "Command R7B",
        contextWindow: 128000,
        inputCostPer1k: 0.0000375,
        outputCostPer1k: 0.00015,
        capabilities: ["code", "fast"],
        tier: "fast",
      },
    ],
  },

  together: {
    id: "together",
    name: "Together AI",
    description: "100+ açık kaynak model (Llama, Qwen, DeepSeek vb.)",
    apiKeyUrl: "https://api.together.xyz/settings/api-keys",
    baseUrl: "https://api.together.xyz/v1",
    authHeader: "bearer",
    color: "#0f6fff",
    icon: "together",
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        contextWindow: 128000,
        inputCostPer1k: 0.00088,
        outputCostPer1k: 0.00088,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "balanced",
      },
      {
        id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
        name: "Llama 3.1 405B",
        contextWindow: 128000,
        inputCostPer1k: 0.003,
        outputCostPer1k: 0.003,
        capabilities: ["code", "reasoning", "long-context"],
        tier: "powerful",
      },
      {
        id: "Qwen/Qwen2.5-Coder-32B-Instruct",
        name: "Qwen 2.5 Coder 32B",
        contextWindow: 32768,
        inputCostPer1k: 0.0005,
        outputCostPer1k: 0.0005,
        capabilities: ["code"],
        tier: "balanced",
      },
      {
        id: "deepseek-ai/DeepSeek-V3",
        name: "DeepSeek V3",
        contextWindow: 64000,
        inputCostPer1k: 0.00027,
        outputCostPer1k: 0.00027,
        capabilities: ["code", "reasoning"],
        tier: "balanced",
      },
    ],
  },
};

export const PROVIDER_LIST = Object.values(PROVIDERS);

export function getProvider(id: ProviderId): ProviderConfig {
  return PROVIDERS[id];
}

export function getModel(provider: ProviderId, modelId: string) {
  return PROVIDERS[provider].models.find((m) => m.id === modelId);
}
